### ISSUE TITLE
Enforce `Prettier` formatting in CI 

### ISSUE THREAD

**Issue by tvolk131** [Resolvr-io/escrow#30]
We added Prettier as our code formatting tool in #29, but we still need to enforce its formatting in CI

**Comment by MAHcodes** [comment]
\+ to prevent failing each time on ci, I suggest using a tool like [husky](https://github.com/typicode/husky) with [lint-staged](https://github.com/lint-staged/lint-staged). This will run prettier only on staged files as a precommit, and ensure that code is formatted consistently before it is committed to the repository, which can save some time and frustration.
